#pragma once

#include <QLoggingCategory>

Q_DECLARE_LOGGING_CATEGORY(nenoserpentStateLog)
Q_DECLARE_LOGGING_CATEGORY(nenoserpentAudioLog)
Q_DECLARE_LOGGING_CATEGORY(nenoserpentInputLog)
Q_DECLARE_LOGGING_CATEGORY(nenoserpentInjectLog)
Q_DECLARE_LOGGING_CATEGORY(nenoserpentLevelLog)
Q_DECLARE_LOGGING_CATEGORY(nenoserpentReplayLog)
